make: ExamGrader.java Exam.java Question.java Answer.java MCAnswer.java MCQuestion.java MCSAAnswer.java MCSAQuestion.java SAAnswer.java SAQuestion.java ScannerFactory.java MCMAQuestion.java MCMAAnswer.java ExamTester.java ExamTaker.java 
	javac ExamGrader.java
clean:
	$(RM) *.class
